### ISSUE TITLE
`Cannot mock "#app/nuxt" because it is already loaded` error in Nuxt environment

### ISSUE THREAD

**Issue by enkot** [nuxt/test-utils#693]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-cr9qis-awh721?file=composables%2Ftests%2FuseTest.test.ts

### Describe the bug

`Cannot mock "#app/nuxt" because it is already loaded` error when using `mockNuxtImport` or `mountSuspended` in tests in Nuxt environment.
Try to run `npm run test`.

**Comment by raichev-dima** [comment]
Same issue, downgrading `vitest` to 1.1.1 makes it work

**Comment by rinux55** [comment]
Hi @danielroe, this seems related to the issue we were pairing on the other day for Funda, where also other mocks with `mockNuxtImport` where not working. We didn't get that error message that time, but they added this error message in the latest `vitest`. Since upgrading to the latest `vitest` we also get this error message. Could you have a look at this? This is currently a major blocker for us to upgrade.

**Comment by pawelmiklas** [comment]
Facing the same issue

**Comment by antoinezanardi** [comment]
I'm facing the same issue as well
